import { writeFileSync, mkdirSync } from "fs";
import type { Command } from "commander";
import { buildProgram } from "../../packages/cli/src/program.js";

const DIR = "docs/reference/cli";
mkdirSync(DIR, { recursive: true });

const program = buildProgram();
const commands = [...program.commands].sort((a: Command, b: Command) =>
  a.name().localeCompare(b.name()),
);

// ponytail: trust commander's own helpInformation — it's the same string `slsv <cmd> --help`
// would print. Per-command page = full help block + subcommand list. Index = command table.
const index: string[] = [
  "<!-- generated by scripts/docs/cli.ts — DO NOT EDIT -->",
  "",
  "# slsv CLI",
  "",
  "Auto-generated from commander in `packages/cli/src/program.ts`. Each command's page is the",
  "exact `--help` output, so it stays honest with every release.",
  "",
  "| Command | Description |",
  "|---------|-------------|",
];

for (const cmd of commands) {
  const name = cmd.name();
  const desc = (cmd.description() ?? "").replace(/\|/g, "\\|");
  index.push(`| [\`${name}\`](${name}.md) | ${desc} |`);

  const page: string[] = [
    "<!-- generated by scripts/docs/cli.ts — DO NOT EDIT -->",
    "",
    `# slsv ${name}`,
    "",
    cmd.description() ? `${cmd.description()}\n` : "",
    "## Help output",
    "",
    "```",
    stripColor(cmd.helpInformation()).trimEnd(),
    "```",
    "",
  ];

  const subs = cmd.commands;
  if (subs.length) {
    page.push("## Subcommands\n");
    for (const sub of subs) {
      page.push(`- \`${name} ${sub.name()}\` — ${sub.description() ?? ""}`);
    }
    page.push("");
  }

  writeFileSync(`${DIR}/${name}.md`, page.join("\n"));
}

writeFileSync(`${DIR}/index.md`, index.join("\n") + "\n");
console.log(`✓ ${DIR}/ (${commands.length} commands)`);

function stripColor(s: string): string {
  // ponytail: build the ANSI escape character at runtime so the source has no literal control char
  // (oxlint's no-control-regex flags the regex form).
  const ESC = String.fromCharCode(0x1b);
  return s.replace(new RegExp(`${ESC}\\[[0-9;]*m`, "g"), "");
}