import { writeFileSync, mkdirSync } from "fs";
import { dirname } from "path";
import { AppConfigSchema } from "../../packages/cli/src/config.js";

const OUT = "docs/reference/slsv-yml.md";
mkdirSync(dirname(OUT), { recursive: true });

// ponytail: zod v4 ships `toJSONSchema()` on every schema — avoids the v3-only
// `zod-to-json-schema` dep entirely.
const json = (AppConfigSchema as any).toJSONSchema() as any;

const topKeys = Object.keys(json.properties ?? {}).sort();
const required = new Set(json.required ?? []);

// ponytail: top-level table + the full JSON Schema dump. The schema is the source of truth —
// any field the table misses is in the JSON Schema block below.
let md = `<!-- generated by scripts/docs/schema.ts — DO NOT EDIT -->

# \`slsv.yml\` reference

Auto-generated from the zod schema in \`packages/cli/src/config.ts:159\`. The schema is the
source of truth; this page exists so the docs site reflects every field, including ones added
in commits.

## Top-level fields

| Field | Required | Type | Notes |
|-------|----------|------|-------|
`;

for (const k of topKeys) {
  const prop = json.properties[k];
  const type = describeType(prop);
  md += `| \`${k}\` | ${required.has(k) ? "yes" : "no"} | ${type} | |\n`;
}

md += `\n## Full JSON Schema\n\n`;
md += "```json\n" + JSON.stringify(json, null, 2) + "\n```\n";

writeFileSync(OUT, md);
console.log(`✓ ${OUT} (${topKeys.length} top-level fields)`);

function describeType(prop: any): string {
  if (!prop) return "any";
  if (prop.$ref) return prop.$ref.replace(/^#\/\$defs\//, "");
  if (prop.enum) return prop.enum.map((v: unknown) => JSON.stringify(v)).join(" \\| ");
  if (prop.const !== undefined) return `literal ${JSON.stringify(prop.const)}`;
  if (prop.anyOf?.length === 2 && prop.anyOf.some((x: any) => x.type === "null")) {
    return describeType(prop.anyOf.find((x: any) => x.type !== "null")) + " \\| null";
  }
  if (prop.anyOf?.length) return prop.anyOf.map(describeType).join(" \\| ");
  if (prop.type === "array") return `${describeType(prop.items)}[]`;
  if (prop.type === "object" && prop.additionalProperties) {
    return `Record<string, ${describeType(prop.additionalProperties)}>`;
  }
  if (prop.type === "object") return "object";
  return prop.type;
}